### ISSUE TITLE
[Feature Request] A way to query for ssh key ID

### ISSUE THREAD

**Issue by p-rintz** [borgbase/borgbase-api-client#1]
Hi there,

Im currently writing an Ansible module to automate the creation of new repositories (and ssh keys). 

Most everything is working, but currently I have no way to query for the ID of an ssh key that is already present in the borgbase account. So currently I cannot write the module to use existing keys, only create new ones and use those.

Thanks.

**Comment by m3nu** [comment]
The GraphQL `sshList` query does exactly that. I can't link to it directly, but you can view it in the API docs browser: https://api.borgbase.com/graphql

Here a usage example in GraphQL:

```
query sshList {
  sshList {
    id
    name
    hashMd5
    keyType
    bits
  }
}
```

**Comment by m3nu** [comment]
I didn't add this as Python example yet, but it should be simple. If you get stuck, let me know and I'll add Python code here.

**Comment by p-rintz** [comment]
I didnt see it in this repo, so I thought it wasnt added yet. Shouldve looked in the GraphQL earlier 👍 
Ive got it working locally already. Though the "owner" and "repoSet" field will throw back a 400 error code if I add it. (just as a side note, not that I will need it)

Thank you for the help.
